# Generated by Django 2.0.3 on 2018-03-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(default='', max_length=254)),
                ('email2', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('budget', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=15, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=30)),
                ('video', models.CharField(blank=True, max_length=6, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('message_id', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('movieId', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('timestamp', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('title', models.CharField(default='', max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254, primary_key=True, serialize=False)),
                ('pw', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recommend',
            unique_together={('email', 'title', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('userId', 'movieId')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('email', 'message_id')},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('email1', 'email2')},
        ),
    ]
