# Generated by Django 2.0 on 2018-04-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('content', models.TextField(default='')),
                ('timestamp', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(default='', max_length=30)),
                ('name2', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=15, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=30)),
                ('video', models.CharField(blank=True, max_length=6, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('movie_id', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('timestamp', models.TextField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('pw', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user_id', 'movie_id')},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('name1', 'name2')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('name', 'timestamp')},
        ),
    ]
