# Generated by Django 2.0.3 on 2018-03-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('message_id', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('title', models.CharField(default='', max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ratingscores', models.FloatField(blank=True, null=True)),
                ('ratingdate', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('title', models.CharField(default='', max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='friendship',
            name='email1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='friendship',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='id2',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('email1', 'email2')},
        ),
        migrations.AlterUniqueTogether(
            name='recommend',
            unique_together={('email', 'title', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('email', 'title', 'year', 'ratingdate')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('email', 'message_id')},
        ),
    ]
