# Generated by Django 2.0 on 2018-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('email', 'timestamp')},
        ),
    ]
