# Generated by Django 2.0 on 2018-04-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180419_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
